[server]
hostname = "localhost"
allow_http_proxy = true
invite_code_required = false
disable_rate_limiting = true

[database]
url = "postgres://happyview:happyview@postgres:5432/pds"

[storage]
path = "/var/lib/tranquil-pds/blobs"

[plc]
directory_url = "http://plc:2582"

[secrets]
allow_insecure = true
