name: Mirror to Tangled

on: [push, delete]

jobs:
  mirror:
    runs-on: depot-ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: "git@tangled.org:gamesgamesgamesgames.games/happyview.git"
          GIT_SSH_PRIVATE_KEY: ${{ secrets.TANGLED_SSH_PRIVATE_KEY }}
          GIT_SSH_NO_VERIFY_HOST: "true"
